apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blitzy-openmrs-core
  description: OpenMRS API and web application code
  tags:
    - java
  annotations:
    github.com/project-slug: Blitzy-Sandbox/blitzy-openmrs-core
    backstage.io/source-location: url:https://github.com/Blitzy-Sandbox/blitzy-openmrs-core/tree/master/
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: blitzy-sandbox
  system: blitzy-sandbox-projects

